export interface TableHead {
  headerTitle: string;
  isSorting: boolean;
}

export interface LeadList {
  agentUserName?: any;
  onlineContactUserName?: any;
  generalName: string;
  customerID: number;
  firstName: string;
  lastName: string;
  leaseState: string;
  regulatoryState: string;
  deviceLogRptgClassCd: number;
  phoneNumber: string;
  initiatedDate: Date;
  accountNote: string;
  dateOfLastOutBoundCall?: any;
  dateOfLastInBoundCall?: any;
  totalOutBoundCalls: number;
  outBoundCallMadeBy?: any;
  outBoundCallInLast3Days: number;
  outBoundCallSinceInstall: number;
  mostRecentDisposition: string;
  createUser: string;
  languageCd?: number;
  agentAssignedToName: string;
  agentAssignedToUser: string;
  agentAssignedDate?: Date;
  followUpAgentName: string;
  followUpAgentUser: string;
  followUpDate?: Date;
  doNotFollowUp: boolean;
  followUpDateAssignedDate?: Date;
  pendAgentName: string;
  pendAgentUser: string;
  pendDate?: Date;
  installAgentName: string;
  installAgentUser: string;
  installDate?: Date;
  requiredDocumentCount: number;
  documentApprovalCount: number;
  nextContactDate?: Date;
  nextContactDateSort: Date;
  nextContactDateSortOrder: number;
  createUserName: string;
  leadAgent: string;
  pendAgent: string;
  followUpAgent: string;
  followUpAgentUserName: string;
  assignedToMe: string;
  name: string;
  languageCode: string;
  haveAllRequiredPaperwork: boolean;
}

export interface Data {
  leadList: LeadList[];
  stateFilterList: string[];
  languageCodeFilterList: string[];
  dispositionFilterList: string[];
  assignedToMeFilterList: string[];
}

export interface RootObject {
  success: boolean;
  statusCode: number;
  message: string;
  data: Data;
}
const leadListMock = [
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1123730,
    firstName: "Eugene",
    lastName: "Grinberg",
    leaseState: "PA",
    regulatoryState: "PA",
    deviceLogRptgClassCd: 256,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: "Install with competitor",
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: "Lost to Comp - Other",
    createUser: "AlokTestAgent",
    languageCd: 199,
    agentAssignedToName: "Alex Killam",
    agentAssignedToUser: "Akillam",
    agentAssignedDate: "2022-12-01T17:17:37.213",
    followUpAgentName: "Alex Killam",
    followUpAgentUser: "Akillam",
    followUpDate: "2022-12-01T17:17:36.213",
    doNotFollowUp: false,
    followUpDateAssignedDate: "2022-12-01T17:17:36.217",
    pendAgentName: "Sher Bond",
    pendAgentUser: "sbond",
    pendDate: "2022-08-17T08:32:36.727",
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 1,
    documentApprovalCount: 0,
    nextContactDate: "2022-12-01T17:17:37.213",
    nextContactDateSort: "2022-12-01T17:17:37.213",
    nextContactDateSortOrder: 1,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "Sher Bond",
    followUpAgent: "Alex Killam",
    followUpAgentUserName: "Akillam",
    assignedToMe: "",
    name: "Eugene Grinberg",
    languageCode: "E",
    haveAllRequiredPaperwork: false,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "Shiree Richardson",
    customerID: 1131058,
    firstName: "RICKY",
    lastName: "DAVIS",
    leaseState: "VA",
    regulatoryState: "VA",
    deviceLogRptgClassCd: 89,
    phoneNumber: null,
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: "obc lvm ",
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: "No Answer - LVM",
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: "Shiree Richardson",
    pendAgentUser: "srichardson",
    pendDate: "2020-11-07T10:40:07.477",
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "Shiree Richardson",
    leadAgent: "Shiree Richardson",
    pendAgent: "Shiree Richardson",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "RICKY DAVIS",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1180006,
    firstName: "Christina",
    lastName: "Cote",
    leaseState: "OR",
    regulatoryState: "OR",
    deviceLogRptgClassCd: 89,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: "obc lm",
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: "No Answer - LVM",
    createUser: "AlokTestAgent",
    languageCd: 199,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: "Wendy Green",
    followUpAgentUser: "wgreen",
    followUpDate: "2022-11-29T17:28:53.427",
    doNotFollowUp: false,
    followUpDateAssignedDate: "2022-11-21T17:31:16.667",
    pendAgentName: "Wendy Green",
    pendAgentUser: "wgreen",
    pendDate: "2021-05-24T20:16:55.46",
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: "2022-11-29T17:28:53.427",
    nextContactDateSort: "2022-11-29T17:28:53.427",
    nextContactDateSortOrder: 1,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "Wendy Green",
    followUpAgent: "Wendy Green",
    followUpAgentUserName: "wgreen",
    assignedToMe: "",
    name: "Christina Cote",
    languageCode: "E",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1197300,
    firstName: "ittest",
    lastName: "testing",
    leaseState: null,
    regulatoryState: null,
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "ittest testing",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1197620,
    firstName: "Laura",
    lastName: "Nguyen",
    leaseState: null,
    regulatoryState: null,
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "Laura Nguyen",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1202538,
    firstName: "Ittestv",
    lastName: "Test",
    leaseState: null,
    regulatoryState: "  ",
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "Ittestv Test",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1202539,
    firstName: "TEST",
    lastName: "TEST",
    leaseState: null,
    regulatoryState: "IA",
    deviceLogRptgClassCd: 0,
    phoneNumber: null,
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "TEST TEST",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1202540,
    firstName: "Ittestamz",
    lastName: "donotcall",
    leaseState: null,
    regulatoryState: "  ",
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "Ittestamz donotcall",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1202541,
    firstName: "ittestVttt",
    lastName: "test",
    leaseState: null,
    regulatoryState: "  ",
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "ittestVttt test",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
  {
    agentUserName: null,
    onlineContactUserName: null,
    generalName: "AlokTestAgent",
    customerID: 1202543,
    firstName: "Ittesamz",
    lastName: "donotcall",
    leaseState: null,
    regulatoryState: "  ",
    deviceLogRptgClassCd: 0,
    phoneNumber: "(515) 204-2558",
    initiatedDate: "2022-12-07T18:58:15.583",
    accountNote: null,
    dateOfLastOutBoundCall: null,
    dateOfLastInBoundCall: null,
    totalOutBoundCalls: 0,
    outBoundCallMadeBy: null,
    outBoundCallInLast3Days: 0,
    outBoundCallSinceInstall: 0,
    mostRecentDisposition: null,
    createUser: "AlokTestAgent",
    languageCd: null,
    agentAssignedToName: null,
    agentAssignedToUser: null,
    agentAssignedDate: null,
    followUpAgentName: null,
    followUpAgentUser: null,
    followUpDate: null,
    doNotFollowUp: false,
    followUpDateAssignedDate: null,
    pendAgentName: null,
    pendAgentUser: null,
    pendDate: null,
    installAgentName: null,
    installAgentUser: null,
    installDate: null,
    requiredDocumentCount: 0,
    documentApprovalCount: 0,
    nextContactDate: null,
    nextContactDateSort: "1971-01-01T00:00:00",
    nextContactDateSortOrder: 2,
    createUserName: "AlokTestAgent",
    leadAgent: "AlokTestAgent",
    pendAgent: "",
    followUpAgent: "",
    followUpAgentUserName: "",
    assignedToMe: "",
    name: "Ittesamz donotcall",
    languageCode: "",
    haveAllRequiredPaperwork: true,
  },
];

const exampleLead = {
  agentUserName: null,
  onlineContactUserName: null,
  generalName: "AlokTestAgent", //Lead agent
  customerID: 1123730,
  firstName: "Eugene", // customer name
  lastName: "Grinberg", // customer name
  leaseState: "PA", //ST
  regulatoryState: "PA", //ST
  deviceLogRptgClassCd: 256,
  phoneNumber: "(515) 204-2558",
  initiatedDate: "2022-12-07T18:58:15.583", //Initiated Date
  accountNote: "Install with competitor", //Account Note
  dateOfLastOutBoundCall: null, // Last OB call
  dateOfLastInBoundCall: null, //Last IB call
  totalOutBoundCalls: 0, //Total OB
  outBoundCallMadeBy: null, //OB Made By
  outBoundCallInLast3Days: 0, //OB 3 Days
  outBoundCallSinceInstall: 0,
  mostRecentDisposition: "Lost to Comp - Other", //Mot recent desposition
  createUser: "AlokTestAgent",
  languageCd: 199,
  agentAssignedToName: "Alex Killam",
  agentAssignedToUser: "Akillam",
  agentAssignedDate: "2022-12-01T17:17:37.213",
  followUpAgentName: "Alex Killam",
  followUpAgentUser: "Akillam",
  followUpDate: "2022-12-01T17:17:36.213",
  doNotFollowUp: false,
  followUpDateAssignedDate: "2022-12-01T17:17:36.217",
  pendAgentName: "Sher Bond", //Pend Agent
  pendAgentUser: "sbond",
  pendDate: "2022-08-17T08:32:36.727", //Pend date
  installAgentName: null,
  installAgentUser: null,
  installDate: null,
  requiredDocumentCount: 1,
  documentApprovalCount: 0,
  nextContactDate: "2022-12-01T17:17:37.213", // Next Contact
  nextContactDateSort: "2022-12-01T17:17:37.213",
  nextContactDateSortOrder: 1,
  createUserName: "AlokTestAgent",
  leadAgent: "AlokTestAgent",
  pendAgent: "Sher Bond",
  followUpAgent: "Alex Killam", //Follow up agent
  followUpAgentUserName: "Akillam",
  assignedToMe: "",
  name: "Eugene Grinberg", //Customer Name
  languageCode: "E", // L
  haveAllRequiredPaperwork: false, //PW
};
